lsa_nav_controller:
  ros__parameters:
    road_scan:
      min_angle_abs: 1.04         # [rad]
      max_angle_abs: 1.48         # [rad]
      angle_increment: 0.00436    # [rad]
      max_range: 5.0              # [m]
      min_range: 0.1              # [m]
    control_freq: 20              # [Hz]
