lang_sam_to_map:
  ros__parameters:
    lsa:
      text_prompt: "side walk"
      box_threshold: 0.3
      text_threshold: 0.25
    node_freq: 20
    interval:
      time: 3.0
      distance: 5
    pointcloud: 
      publish: false
      voxel_grid:
        leaf_size: 0.025
    valid_threshold:
      min: 0.3
      max: 10.0
    map:
      resolution: 0.1