lang_sam_to_map:
  ros__parameters:
    lsa:
      text_prompt: "side walk"
      box_threshold: 0.3
      text_threshold: 0.25
    node_freq: 20
    interval:
      time: 3.0
      distance: 5
    pointcloud: 
      publish: true
      voxel_grid:
        leaf_size: 0.05
    valid_threshold:
      min: 1.5
      max: 20.0
    map:
      resolution: 0.05
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"